### ISSUE TITLE
SOLVIS_GRAPHQL_API Feature: Geojson styling

### ISSUE THREAD

**Issue by benjamineac** [GNS-Science/solvis-graphql-api#5]
Want to be able to configure the styling options so the leaflet component can use the styling supplied by the geojson instead of providing its own.
Done when:
- [x] Can configure the stroke property of rupture results and location polygons.
- [x] Can configure the fill property of rupture results and location polygons.

**Comment by chrisbc** [comment]
@benjamineac example query  below:

Notes: 
 - field `geojson` was renamed to `ruptures_geojson` for GROKing
 - use https://htmlcolorcodes.com/color-names/ or hex codes "xcc00ff"
 - style fields have default values, so everything is optional here... but the defaults are probably quite ugly :)

```  SOLVIS_analyse_solution (
    input:{
      solution_id:"U2NhbGVkSW52ZXJzaW9uU29sdXRpb246MTIwNzIy"
    	location_codes: ["WLG", "LVN"]
      radius_km: 10
      minimum_mag:8.2
      location_area_style: {
        stroke_color: "gold"
      	stroke_width: 1
        stroke_opacity: 0.5
        fill_color:"gold"
        fill_opacity: 0.5
      } 
      fault_trace_style: {
        stroke_color: "silver"
      	stroke_width: 3
        stroke_opacity:1      
      } 
    }) {
    analysis {
      ruptures_geojson
      location_geojson
      solution_id
    }    
  }
}
