### ISSUE TITLE
SOLVIS_GRAPHQL_API Feature: all ruptures

### ISSUE THREAD

**Issue by chrisdicaprio** [GNS-Science/solvis-graphql-api#6]
We want to get **fault sections** ~ruptures~ without geographic filter (i.e. no need to specify location and radius). Retain filter on magnitude and rate

**Comment by chrisbc** [comment]
example query: 

```query {
  SOLVIS_analyse_solution (
    input:{
      solution_id:"U2NhbGVkSW52ZXJzaW9uU29sdXRpb246MTIwNzIy"
      location_codes: []
      ...etc etc   
  }
}

**Comment by chrisbc** [comment]
@chrisdicaprio sorry I closed this and I shoudn't have . It's WIP
